server:
  port: ${SERVER_PORT:10037}
  tomcat:
    max-http-form-post-size: 10GB
keiskei:
  file:
    path: ${FILE_PATH:/temp/file/}
    temp-path: ${FILE_PATH_TEMP:/temp/file/tmp/}
spring:
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB